### ISSUE TITLE
not work with yes command

### ISSUE THREAD

**Issue by Wing924** [Songmu/prompter#2]
### my code

```go
// main.go
import (
	"fmt"

	"github.com/Songmu/prompter"
)

func main() {
	if prompter.YN("do you like sushi?", false) {
		fmt.Println("Nice!")
	} else {
		fmt.Println("It's Okay.")
	}
}
```

### What I do
```bash
yes | go run main.go
```
I expect it outputs `Nice!` but is `It's Okay.`

### Reason

https://github.com/Songmu/prompter/blob/9b5529e9ffd102d5a266d0e3b53526259c2c0b68/prompter.go#L63-L68

no way to make it block and read from stdin

**Comment by Songmu** [comment]
I think input to the prompt should be given from the terminal, and it is a bad hack to force input to the prompt with the yes command.

If the STDIN or STDOUT are not connected to the terminal, the default value is used. this is this library specification. If you do not want to use the default value here, you can avoid it with another setting on your application side.

For example:

```go
func main() {
    likeSushi := os.Getenv("LIKE_SUSHI") == "1"
    if likeSushi || prompter.YN("do you like sushi?", false) {
        fmt.Println("Nice!")
    } else {
        fmt.Println("It's Okay.")
    }
}
```

**Comment by Wing924** [comment]
> If the STDIN or STDOUT are not connected to the terminal, the default value is used. this is this library specification. 

Normal unix like application will be blocked on there. It would be nice if we have block mode.

**Comment by Songmu** [comment]
In general, prompts should not interfere with automation or connection with other programs.

This is in line with the philosophy of "Avoid captive user interface" in the book "The unix philosophy". So "prompter" is also designed not to block when not in interactive mode.

The method of forcing yes as your example is just an ad hoc way to badly behaved commands. I don't want to add an option to do that bad behavior to "prompter".

If you have any good examples other than the "yes" command, I might consider to add option.

Thanks.

**Comment by Songmu** [comment]
> Normal unix like application will be blocked on there. 

Unfortunately, there may be many such applications, but I think it is simply a lack of consideration.

**Comment by Wing924** [comment]
Since it's a philosophy war, I'll stop to discuss it and find another way.

**Comment by Songmu** [comment]
Thanks.

Unfortunately, I didn't know exactly what you were having trouble with. If you explain a little more specifically, I may be able to give some advice.

**Comment by Wing924** [comment]
@Songmu 
I created an interactive app using this lib. This app has many yes/no questions.
I want to run the app via script.

The default answers should be `false` on CLI due to fail safe, but I want them be `true` when run via script.

**Comment by Songmu** [comment]
In such a case, I think that it is a common design to provide a command-line option such as `--force` and treat it as 'yes' when it is true.

Or you can use an environment variable such as `YOURAPP_FORCE_YES` and check it being truthy or not.
